stages:
  - build_test
  - push_test
  - deploy_test

variables:
  DOCKER_HOST: 'unix:///var/run/docker.sock'
  REMOTE_SERVER_IP: $SERVER_IP
  REMOTE_SERVER_USER: $SERVER_USER
  SSH_PRIVATE_KEY: $ID_RSA
  SSH_CMD: 'ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$REMOTE_SERVER_IP'

build_test:
  image: docker:stable
  stage: build_test
  only:
    - test
  script:
    - docker info # Проверка подключения к Docker
    - docker system prune -a -f
    - docker build --build-arg API_1C_URL="$API_1C_URL" --build-arg CRYPTO_SECRET_KEY="$CRYPTO_SECRET_KEY" --build-arg CRYPTO_IV="$CRYPTO_IV" --build-arg SECRET_COOKIE_PASSWORD="$SECRET_COOKIE_PASSWORD" -t $CI_REGISTRY_IMAGE:latest .

push_test:
  image: docker:stable
  stage: push_test
  only:
    - test
  script:
    - docker login $CI_REGISTRY -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_test:
  image: alpine:latest
  stage: deploy_test
  only:
    - test
  before_script:
    - echo "$ID_RSA" > /tmp/deploy_key.pem
    - chmod 600 /tmp/deploy_key.pem
    - apk update && apk add openssh-client
  script:
    # 1. Docker login
    - $SSH_CMD "echo $DOCKER_TOKEN | docker login $CI_REGISTRY -u $DOCKER_USER --password-stdin"

    # 2. Pull образа
    - $SSH_CMD "docker pull $DOCKER_IMAGE_NAME"

    # 3. Остановка и удаление старого контейнера
    - $SSH_CMD "docker container rm -f new-lk || true"

    # 4. Запуск нового контейнера
    - $SSH_CMD "docker run --restart unless-stopped -d -p 3000:3000 --name new-lk -e API_1C_URL="$API_1C_URL" -e CRYPTO_SECRET_KEY="$CRYPTO_SECRET_KEY" -e CRYPTO_IV="$CRYPTO_IV" -e SECRET_COOKIE_PASSWORD="$SECRET_COOKIE_PASSWORD" $DOCKER_IMAGE_NAME"

  after_script:
    - rm -f /tmp/deploy_key.pem # Очистка ключа
