stages:
  - build_test
  - push_test
  - deploy_test

build_test:
  image: docker:stable
  stage: build_test
  only:
    - test
  script:
    - docker system prune -a -f
    - docker build -t registry.krasrm.com/pahapasha11/new-lk .

push_test:
  stage: push_test
  only:
    - test
  script:
    - docker login registry.krasrm.com -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push registry.krasrm.com/pahapasha11/new-lk

deploy_test:
  image: alpine:latest
  stage: deploy_test
  only:
    - test
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$REMOTE_SERVER_IP "docker login registry.krasrm.com -u $DOCKER_USER -p $DOCKER_TOKEN"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$REMOTE_SERVER_IP "docker pull $DOCKER_IMAGE_NAME"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$REMOTE_SERVER_IP "docker container rm -f new-lk-krasrm-com || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$REMOTE_SERVER_IP "docker run --restart unless-stopped -d -p 8080:80 --name new-lk-krasrm-com $DOCKER_IMAGE_NAME"
