version: '3'

services:
  frontend:
    image: registry.krasrm.com/pahapasha11/new-lk
    restart: always
    build: .
    ports:
      - 80:80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - '80:80'
    depends_on:
      - newLk
