version: '3.8' # Обновил версию

services:
  frontend:
    image: registry.krasrm.com/pahapasha11/new-lk:${TAG:-latest} # Использование переменной для тега
    restart: always
    env_file: .env
    build:
      context: .
      args:
        - API_1C_URL=${API_1C_URL}
        - CRYPTO_SECRET_KEY=${CRYPTO_SECRET_KEY}
        - CRYPTO_IV=${CRYPTO_IV}
        - SECRET_COOKIE_PASSWORD=${SECRET_COOKIE_PASSWORD}
        - CACHE_BUST=${CACHE_BUST:-1} # Добавил для инвалидации кэша
    ports:
      - 3000:3000
    environment:
      - API_1C_URL=${API_1C_URL}
      - CRYPTO_SECRET_KEY=${CRYPTO_SECRET_KEY}
      - CRYPTO_IV=${CRYPTO_IV}
      - SECRET_COOKIE_PASSWORD=${SECRET_COOKIE_PASSWORD}
    logging: # Добавил настройки логирования
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck: # Добавил проверку здоровья
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
