version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    # Не запускаем, только билдим для экспорта

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - nextjs
