export { Description } from './description/Description'
export { ArticleDiv } from './articleDiv/ArticleDiv'
export { ResponsibleCard } from './responsibleCard/ResponsibleCard'
export { TabsWrapper } from './tabs/TabsWrapper'
export { PriceTableButton } from './cost/PriceTableButton'
