import '@/styles/global.scss'
import Footer from '@/ui/Footer/Footer'
import Header from '@/ui/Header/Header'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const montserrat = localFont({
  src: [
    {
      path: '../public/font/Montserrat-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/font/Montserrat-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/font/Montserrat-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/font/Montserrat-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/font/Montserrat-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <div className="layout">
          <Header />
          <main className="content">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
